places = ['Beijing','Shanghai','Nanjing','Hangzhou','Shenzheng']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
